Error: worked on ML pipeline error
Still not fixed, but hopefully made progress in ML pipeline. Added multi-output classifier and fixed feature / target variables. Probably need to fix more of multi-output classifier.